version: '3'
services:

  ## Router
  router01:
    image: mongo:latest
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb

  ## Config Servers
  configsvr01:
    image: mongo:latest
    container_name: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27120:27017
    restart: always


  shard01-a:
    image: mongo:latest
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27123:27017
    restart: always

  ## Shards 02
  shard02-a:
    image: mongo:latest
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27126:27017
    restart: always

  # Приложение
  mongo-sharding:
    container_name: mongo-sharding
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - router01
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://router01:27017/somedb"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:

  mongodb_cluster_configsvr01_db:
  mongodb_cluster_configsvr01_config:

  mongodb_cluster_shard01_a_db:
  mongodb_cluster_shard01_a_config:

  mongodb_cluster_shard02_a_db:
  mongodb_cluster_shard02_a_config: